version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - echo Nothing to do yet
artifacts:
  type: zip
  files:
    - index.html
    - favicon.ico
    - Clark_David_CV_do.pdf
    - styles/*
    - images/*
